// MODULE top, AUTOMATICALLY GENERATED BY PYTHON

/**/
`default_nettype wire


module top (
    output miso,
    output lmx_clk,
    input lmx_muxout,
    output lmx_ce,
    output [0:0] test_low_freq_marion2018_up_led0_sync_ext,
    input cs_n,
    output lmx_le,
    input [0:0] adc16_clk_line_p,
    output [2:0] adc0_adc3wire_sdata,
    input [0:0] adc16_clk_line_n,
    output [2:0] adc_rst_n,
    input sys_clk_p,
    output [0:0] test_low_freq_marion2018_up_led1_new_acc_ext,
    output lmx_be,
    input mosi,
    input [11:0] adc16_ser_a_n,
    input [11:0] adc16_ser_a_p,
    output adc0_adc3wire_csn1,
    output adc0_adc3wire_csn2,
    output [0:0] clk_sel_b,
    output lmx_data,
    output [0:0] clk_sel_a,
    input sclk,
    input [11:0] adc16_ser_b_p,
    input [11:0] adc16_ser_b_n,
    output adc0_adc3wire_csn3,
    output [2:0] adc_pd,
    input sys_clk_n,
    output [2:0] adc0_adc3wire_sclk
  );



  localparam TEST_LOW_FREQ_MARION2018_UP_CNT_RST_WBID0 = 0;
  localparam TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_PERIOD_VAR_WBID0 = 1;
  localparam TEST_LOW_FREQ_MARION2018_UP_A_POL0_WBID0 = 2;
  localparam TEST_LOW_FREQ_MARION2018_UP_A_POL1_WBID0 = 3;
  localparam TEST_LOW_FREQ_MARION2018_UP_ACC_CNT_WBID0 = 4;
  localparam XADC_INST_WBID0 = 5;
  localparam SYS_BLOCK_INST_WBID0 = 6;
  localparam TEST_LOW_FREQ_MARION2018_UP_A_REAL_WBID0 = 7;
  localparam ADC16_WB_RAM1_WBID0 = 8;
  localparam ADC16_WB_RAM0_WBID0 = 9;
  localparam ADC16_WB_RAM2_WBID0 = 10;
  localparam TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_PERIOD_SEL_WBID0 = 11;
  localparam TEST_LOW_FREQ_MARION2018_UP_SYNC_CNT_WBID0 = 12;
  localparam TEST_LOW_FREQ_MARION2018_UP_A_IMAGINARY_WBID0 = 13;
  localparam TEST_LOW_FREQ_MARION2018_UP_GAIN_WBID0 = 14;
  localparam SNAP_ADC_ADC16_USE_SYNTH_WBID0 = 15;
  localparam TEST_LOW_FREQ_MARION2018_UP_FFT_SHIFT_WBID0 = 16;
  localparam LMX2581_CONTROLLER_INST_WBID0 = 17;
  localparam TEST_LOW_FREQ_MARION2018_UP_ACC_LEN_WBID0 = 18;
  localparam WB_ADC16_CONTROLLER_WBID0 = 19;
  localparam TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_WBID0 = 20;
  localparam N_WB_SLAVES = 21;
  localparam SLAVE_BASE = {
    32'h0001b368, // sync_gen1_sync
    32'h0001b268, // adc16_controller
    32'h0001b264, // acc_len
    32'h0001b260, // lmx_ctrl
    32'h0001b25c, // fft_shift
    32'h0001b258, // adc16_use_synth
    32'h0001b254, // gain
    32'h00019254, // a_imaginary
    32'h00019250, // sync_cnt
    32'h0001924c, // sync_gen1_sync_period_sel
    32'h0001824c, // adc16_wb_ram2
    32'h0001724c, // adc16_wb_ram0
    32'h0001624c, // adc16_wb_ram1
    32'h0001424c, // a_real
    32'h0001420c, // sys_block
    32'h0001400c, // xadc
    32'h00014008, // acc_cnt
    32'h00012008, // a_pol1
    32'h00010008, // a_pol0
    32'h00010004, // sync_gen1_sync_period_var
    32'h00010000 // cnt_rst
    };
  localparam SLAVE_HIGH = {
    32'h0001b36b, // sync_gen1_sync
    32'h0001b367, // adc16_controller
    32'h0001b267, // acc_len
    32'h0001b263, // lmx_ctrl
    32'h0001b25f, // fft_shift
    32'h0001b25b, // adc16_use_synth
    32'h0001b257, // gain
    32'h0001b253, // a_imaginary
    32'h00019253, // sync_cnt
    32'h0001924f, // sync_gen1_sync_period_sel
    32'h0001924b, // adc16_wb_ram2
    32'h0001824b, // adc16_wb_ram0
    32'h0001724b, // adc16_wb_ram1
    32'h0001624b, // a_real
    32'h0001424b, // sys_block
    32'h0001420b, // xadc
    32'h0001400b, // acc_cnt
    32'h00014007, // a_pol1
    32'h00012007, // a_pol0
    32'h00010007, // sync_gen1_sync_period_var
    32'h00010003 // cnt_rst
    };

  wire idelay_rdy;
  wire [31:0] wbs_adr_o;
  wire [9:0] test_low_freq_marion2018_up_a_pol0_addr;
  wire [9:0] test_low_freq_marion2018_up_a_pol1_addr;
  wire [31:0] test_low_freq_marion2018_up_acc_cnt_user_data_in;
  wire adc16_snap_we;
  wire [31:0] test_low_freq_marion2018_up_sync_gen1_sync_user_data_out;
  wire [7:0] test_low_freq_marion2018_up_snap_adc_c3;
  wire [7:0] test_low_freq_marion2018_up_snap_adc_a4;
  wire [7:0] test_low_freq_marion2018_up_snap_adc_a3;
  wire [7:0] test_low_freq_marion2018_up_snap_adc_a2;
  wire [7:0] test_low_freq_marion2018_up_snap_adc_a1;
  wire adc0_clk;
  wire [9:0] test_low_freq_marion2018_up_a_real_addr;
  wire [63:0] adc16_delay_rst;
  wire test_low_freq_marion2018_up_a_real_we;
  wire [63:0] test_low_freq_marion2018_up_a_real_data_out;
  wire [20:0] wbs_stb_o;
  wire [31:0] test_low_freq_marion2018_up_sync_cnt_user_data_in;
  wire [31:0] test_low_freq_marion2018_up_cnt_rst_user_data_out;
  wire [0:0] test_low_freq_marion2018_up_led0_sync_gateway;
  wire [63:0] test_low_freq_marion2018_up_a_pol0_data_out;
  wire [31:0] wbm_dat_i;
  wire sys_clk270;
  wire [3:0] wbm_sel_o;
  wire adc16_snap_req;
  wire [1:0] adc16_locked;
  wire wb_rst_i;
  wire [671:0] wbs_dat_i;
  wire user_clk;
  wire sys_rst;
  wire adc0_clk180;
  wire [31:0] test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out;
  wire [31:0] wbm_dat_o;
  wire [7:0] test_low_freq_marion2018_up_snap_adc_c1;
  wire wb_clk_i;
  wire [1:0] adc16_demux_mode;
  wire [63:0] test_low_freq_marion2018_up_a_imaginary_data_in;
  wire [31:0] wbs_dat_o;
  wire user_clk270;
  wire wbm_err_i;
  wire test_low_freq_marion2018_up_a_pol0_we;
  wire [63:0] test_low_freq_marion2018_up_a_pol1_data_out;
  wire [7:0] test_low_freq_marion2018_up_snap_adc_b3;
  wire [63:0] test_low_freq_marion2018_up_a_pol1_data_in;
  wire test_low_freq_marion2018_up_a_imaginary_we;
  wire [7:0] test_low_freq_marion2018_up_snap_adc_c2;
  wire [0:0] test_low_freq_marion2018_up_led1_new_acc_gateway;
  wire [20:0] wbs_cyc_o;
  wire [63:0] test_low_freq_marion2018_up_a_imaginary_data_out;
  wire [31:0] wbm_adr_o;
  wire wbm_cyc_o;
  wire [63:0] adc16_iserdes_bitslip;
  wire [7:0] test_low_freq_marion2018_up_snap_adc_c4;
  wire wbm_we_o;
  wire sys_clk180;
  wire user_clk180;
  wire [31:0] test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out;
  wire [20:0] wbs_ack_i;
  wire [9:0] adc16_snap_addr;
  wire [31:0] test_low_freq_marion2018_up_acc_len_user_data_out;
  wire [63:0] test_low_freq_marion2018_up_a_real_data_in;
  wire clk_200;
  wire test_low_freq_marion2018_up_a_pol1_we;
  wire [31:0] test_low_freq_marion2018_up_gain_user_data_out;
  wire wbm_ack_i;
  wire adc16_reset;
  wire wbs_we_o;
  wire [31:0] snap_adc_adc16_use_synth_user_data_out;
  wire adc0_clk270;
  wire [9:0] test_low_freq_marion2018_up_a_imaginary_addr;
  wire user_clk90;
  wire [7:0] test_low_freq_marion2018_up_snap_adc_b4;
  wire [31:0] test_low_freq_marion2018_up_fft_shift_user_data_out;
  wire [7:0] test_low_freq_marion2018_up_snap_adc_b2;
  wire [63:0] test_low_freq_marion2018_up_a_pol0_data_in;
  wire [4:0] adc16_delay_tap;
  wire [7:0] test_low_freq_marion2018_up_snap_adc_b1;
  wire [3:0] wbs_sel_o;
  wire sys_clk;
  wire wbm_stb_o;
  wire sys_clk90;
  wire adc0_clk90;
  wire [20:0] wbs_err_i;

  // test_low_freq_marion2018_up_cnt_rst
  wb_register_ppc2simulink  test_low_freq_marion2018_up_cnt_rst (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[TEST_LOW_FREQ_MARION2018_UP_CNT_RST_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[TEST_LOW_FREQ_MARION2018_UP_CNT_RST_WBID0]),
    .user_clk(user_clk),
    .wb_stb_i(wbs_stb_o[TEST_LOW_FREQ_MARION2018_UP_CNT_RST_WBID0]),
    .wb_cyc_i(wbs_cyc_o[TEST_LOW_FREQ_MARION2018_UP_CNT_RST_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .wb_dat_o(wbs_dat_i[(TEST_LOW_FREQ_MARION2018_UP_CNT_RST_WBID0+1)*32-1:(TEST_LOW_FREQ_MARION2018_UP_CNT_RST_WBID0)*32]),
    .user_data_out(test_low_freq_marion2018_up_cnt_rst_user_data_out),
    .wb_adr_i(wbs_adr_o)
  );

  // test_low_freq_marion2018_up_sync_gen1_sync_period_var
  wb_register_ppc2simulink  test_low_freq_marion2018_up_sync_gen1_sync_period_var (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_PERIOD_VAR_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_PERIOD_VAR_WBID0]),
    .user_clk(user_clk),
    .wb_stb_i(wbs_stb_o[TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_PERIOD_VAR_WBID0]),
    .wb_cyc_i(wbs_cyc_o[TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_PERIOD_VAR_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .wb_dat_o(wbs_dat_i[(TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_PERIOD_VAR_WBID0+1)*32-1:(TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_PERIOD_VAR_WBID0)*32]),
    .user_data_out(test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out),
    .wb_adr_i(wbs_adr_o)
  );

  // test_low_freq_marion2018_up_a_pol0
  wb_bram #(
    .LOG_USER_WIDTH(6),
    .USER_ADDR_BITS(10),
    .N_REGISTERS(0)
  ) test_low_freq_marion2018_up_a_pol0 (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[TEST_LOW_FREQ_MARION2018_UP_A_POL0_WBID0]),
    .user_din(test_low_freq_marion2018_up_a_pol0_data_in),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[TEST_LOW_FREQ_MARION2018_UP_A_POL0_WBID0]),
    .user_clk(user_clk),
    .wb_stb_i(wbs_stb_o[TEST_LOW_FREQ_MARION2018_UP_A_POL0_WBID0]),
    .wb_cyc_i(wbs_cyc_o[TEST_LOW_FREQ_MARION2018_UP_A_POL0_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .user_addr(test_low_freq_marion2018_up_a_pol0_addr),
    .user_dout(test_low_freq_marion2018_up_a_pol0_data_out),
    .user_we(test_low_freq_marion2018_up_a_pol0_we),
    .wb_dat_o(wbs_dat_i[(TEST_LOW_FREQ_MARION2018_UP_A_POL0_WBID0+1)*32-1:(TEST_LOW_FREQ_MARION2018_UP_A_POL0_WBID0)*32]),
    .wb_adr_i(wbs_adr_o)
  );

  // test_low_freq_marion2018_up_a_pol1
  wb_bram #(
    .LOG_USER_WIDTH(6),
    .USER_ADDR_BITS(10),
    .N_REGISTERS(0)
  ) test_low_freq_marion2018_up_a_pol1 (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[TEST_LOW_FREQ_MARION2018_UP_A_POL1_WBID0]),
    .user_din(test_low_freq_marion2018_up_a_pol1_data_in),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[TEST_LOW_FREQ_MARION2018_UP_A_POL1_WBID0]),
    .user_clk(user_clk),
    .wb_stb_i(wbs_stb_o[TEST_LOW_FREQ_MARION2018_UP_A_POL1_WBID0]),
    .wb_cyc_i(wbs_cyc_o[TEST_LOW_FREQ_MARION2018_UP_A_POL1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .user_addr(test_low_freq_marion2018_up_a_pol1_addr),
    .user_dout(test_low_freq_marion2018_up_a_pol1_data_out),
    .user_we(test_low_freq_marion2018_up_a_pol1_we),
    .wb_dat_o(wbs_dat_i[(TEST_LOW_FREQ_MARION2018_UP_A_POL1_WBID0+1)*32-1:(TEST_LOW_FREQ_MARION2018_UP_A_POL1_WBID0)*32]),
    .wb_adr_i(wbs_adr_o)
  );

  // test_low_freq_marion2018_up_acc_cnt
  wb_register_simulink2ppc  test_low_freq_marion2018_up_acc_cnt (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[TEST_LOW_FREQ_MARION2018_UP_ACC_CNT_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[TEST_LOW_FREQ_MARION2018_UP_ACC_CNT_WBID0]),
    .user_clk(user_clk),
    .wb_stb_i(wbs_stb_o[TEST_LOW_FREQ_MARION2018_UP_ACC_CNT_WBID0]),
    .wb_cyc_i(wbs_cyc_o[TEST_LOW_FREQ_MARION2018_UP_ACC_CNT_WBID0]),
    .user_data_in(test_low_freq_marion2018_up_acc_cnt_user_data_in),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .wb_dat_o(wbs_dat_i[(TEST_LOW_FREQ_MARION2018_UP_ACC_CNT_WBID0+1)*32-1:(TEST_LOW_FREQ_MARION2018_UP_ACC_CNT_WBID0)*32]),
    .wb_adr_i(wbs_adr_o)
  );

  // test_low_freq_marion2018_up_snap_adc
  adc16_interface #(
    .G_NUM_CLOCKS(1),
    .G_ZDOK_REV(2),
    .G_NUM_UNITS(3),
    .ADC_RESOLUTION(8),
    .ADC_DATA_WIDTH(8)
  ) test_low_freq_marion2018_up_snap_adc (
    .snap_we(adc16_snap_we),
    .snap_addr(adc16_snap_addr),
    .ser_b_p(adc16_ser_b_p),
    .snap_req(adc16_snap_req),
    .delay_tap(adc16_delay_tap),
    .b4(test_low_freq_marion2018_up_snap_adc_b4),
    .b1(test_low_freq_marion2018_up_snap_adc_b1),
    .b2(test_low_freq_marion2018_up_snap_adc_b2),
    .b3(test_low_freq_marion2018_up_snap_adc_b3),
    .ser_b_n(adc16_ser_b_n),
    .ser_a_n(adc16_ser_a_n),
    .clk_line_n(adc16_clk_line_n),
    .fabric_clk(adc0_clk),
    .clk_line_p(adc16_clk_line_p),
    .fabric_clk_180(adc0_clk180),
    .fabric_clk_270(adc0_clk270),
    .fabric_clk_90(adc0_clk90),
    .clk_frame_n(0),
    .a1(test_low_freq_marion2018_up_snap_adc_a1),
    .delay_rst(adc16_delay_rst),
    .a2(test_low_freq_marion2018_up_snap_adc_a2),
    .clk_frame_p(0),
    .a4(test_low_freq_marion2018_up_snap_adc_a4),
    .c3(test_low_freq_marion2018_up_snap_adc_c3),
    .c2(test_low_freq_marion2018_up_snap_adc_c2),
    .c1(test_low_freq_marion2018_up_snap_adc_c1),
    .c4(test_low_freq_marion2018_up_snap_adc_c4),
    .reset(adc16_reset),
    .ser_a_p(adc16_ser_a_p),
    .locked(adc16_locked),
    .a3(test_low_freq_marion2018_up_snap_adc_a3),
    .demux_mode(adc16_demux_mode),
    .iserdes_bitslip(adc16_iserdes_bitslip)
  );

  // xps:xadc0
  xadc  xadc_inst (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[XADC_INST_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[XADC_INST_WBID0]),
    .wb_stb_i(wbs_stb_o[XADC_INST_WBID0]),
    .wb_cyc_i(wbs_cyc_o[XADC_INST_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .wb_dat_o(wbs_dat_i[(XADC_INST_WBID0+1)*32-1:(XADC_INST_WBID0)*32]),
    .wb_adr_i(wbs_adr_o)
  );

  // None
  sys_block #(
    .BOARD_ID(12),
    .REV_MAJ(12),
    .REV_MIN(0),
    .REV_RCS(32)
  ) sys_block_inst (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[SYS_BLOCK_INST_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[SYS_BLOCK_INST_WBID0]),
    .user_clk(user_clk),
    .wb_stb_i(wbs_stb_o[SYS_BLOCK_INST_WBID0]),
    .wb_cyc_i(wbs_cyc_o[SYS_BLOCK_INST_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .wb_dat_o(wbs_dat_i[(SYS_BLOCK_INST_WBID0+1)*32-1:(SYS_BLOCK_INST_WBID0)*32]),
    .wb_adr_i(wbs_adr_o)
  );

  // None
  spi_wb_bridge #(
    .LITTLE_ENDIAN(1)
  ) spi_wb_bridge_inst (
    .miso(miso),
    .wbm_dat_i(wbm_dat_i),
    .wb_rst_i(wb_rst_i),
    .wbm_ack_i(wbm_ack_i),
    .sclk(sclk),
    .mosi(mosi),
    .wbm_cyc_o(wbm_cyc_o),
    .wb_clk_i(wb_clk_i),
    .wbm_we_o(wbm_we_o ),
    .cs_n(cs_n),
    .wbm_err_i(wbm_err_i),
    .wbm_sel_o(wbm_sel_o),
    .wbm_stb_o(wbm_stb_o),
    .wbm_dat_o(wbm_dat_o),
    .new_cmd_stb(),
    .wbm_adr_o(wbm_adr_o)
  );

  // test_low_freq_marion2018_up_a_real
  wb_bram #(
    .LOG_USER_WIDTH(6),
    .USER_ADDR_BITS(10),
    .N_REGISTERS(1)
  ) test_low_freq_marion2018_up_a_real (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[TEST_LOW_FREQ_MARION2018_UP_A_REAL_WBID0]),
    .user_din(test_low_freq_marion2018_up_a_real_data_in),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[TEST_LOW_FREQ_MARION2018_UP_A_REAL_WBID0]),
    .user_clk(user_clk),
    .wb_stb_i(wbs_stb_o[TEST_LOW_FREQ_MARION2018_UP_A_REAL_WBID0]),
    .wb_cyc_i(wbs_cyc_o[TEST_LOW_FREQ_MARION2018_UP_A_REAL_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .user_addr(test_low_freq_marion2018_up_a_real_addr),
    .user_dout(test_low_freq_marion2018_up_a_real_data_out),
    .user_we(test_low_freq_marion2018_up_a_real_we),
    .wb_dat_o(wbs_dat_i[(TEST_LOW_FREQ_MARION2018_UP_A_REAL_WBID0+1)*32-1:(TEST_LOW_FREQ_MARION2018_UP_A_REAL_WBID0)*32]),
    .wb_adr_i(wbs_adr_o)
  );

  // Embedded ADC16 bram
  wb_bram #(
    .LOG_USER_WIDTH(5),
    .USER_ADDR_BITS(10),
    .N_REGISTERS(2)
  ) adc16_wb_ram1 (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[ADC16_WB_RAM1_WBID0]),
    .user_din({test_low_freq_marion2018_up_snap_adc_b1,test_low_freq_marion2018_up_snap_adc_b2,test_low_freq_marion2018_up_snap_adc_b3,test_low_freq_marion2018_up_snap_adc_b4}),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[ADC16_WB_RAM1_WBID0]),
    .user_clk(adc0_clk),
    .wb_stb_i(wbs_stb_o[ADC16_WB_RAM1_WBID0]),
    .wb_cyc_i(wbs_cyc_o[ADC16_WB_RAM1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .user_addr(adc16_snap_addr),
    .user_dout(),
    .user_we(adc16_snap_we),
    .wb_dat_o(wbs_dat_i[(ADC16_WB_RAM1_WBID0+1)*32-1:(ADC16_WB_RAM1_WBID0)*32]),
    .wb_adr_i(wbs_adr_o)
  );

  // Embedded ADC16 bram
  wb_bram #(
    .LOG_USER_WIDTH(5),
    .USER_ADDR_BITS(10),
    .N_REGISTERS(2)
  ) adc16_wb_ram0 (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[ADC16_WB_RAM0_WBID0]),
    .user_din({test_low_freq_marion2018_up_snap_adc_a1,test_low_freq_marion2018_up_snap_adc_a2,test_low_freq_marion2018_up_snap_adc_a3,test_low_freq_marion2018_up_snap_adc_a4}),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[ADC16_WB_RAM0_WBID0]),
    .user_clk(adc0_clk),
    .wb_stb_i(wbs_stb_o[ADC16_WB_RAM0_WBID0]),
    .wb_cyc_i(wbs_cyc_o[ADC16_WB_RAM0_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .user_addr(adc16_snap_addr),
    .user_dout(),
    .user_we(adc16_snap_we),
    .wb_dat_o(wbs_dat_i[(ADC16_WB_RAM0_WBID0+1)*32-1:(ADC16_WB_RAM0_WBID0)*32]),
    .wb_adr_i(wbs_adr_o)
  );

  // Embedded ADC16 bram
  wb_bram #(
    .LOG_USER_WIDTH(5),
    .USER_ADDR_BITS(10),
    .N_REGISTERS(2)
  ) adc16_wb_ram2 (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[ADC16_WB_RAM2_WBID0]),
    .user_din({test_low_freq_marion2018_up_snap_adc_c1,test_low_freq_marion2018_up_snap_adc_c2,test_low_freq_marion2018_up_snap_adc_c3,test_low_freq_marion2018_up_snap_adc_c4}),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[ADC16_WB_RAM2_WBID0]),
    .user_clk(adc0_clk),
    .wb_stb_i(wbs_stb_o[ADC16_WB_RAM2_WBID0]),
    .wb_cyc_i(wbs_cyc_o[ADC16_WB_RAM2_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .user_addr(adc16_snap_addr),
    .user_dout(),
    .user_we(adc16_snap_we),
    .wb_dat_o(wbs_dat_i[(ADC16_WB_RAM2_WBID0+1)*32-1:(ADC16_WB_RAM2_WBID0)*32]),
    .wb_adr_i(wbs_adr_o)
  );

  // test_low_freq_marion2018_up_sync_gen1_sync_period_sel
  wb_register_ppc2simulink  test_low_freq_marion2018_up_sync_gen1_sync_period_sel (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_PERIOD_SEL_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_PERIOD_SEL_WBID0]),
    .user_clk(user_clk),
    .wb_stb_i(wbs_stb_o[TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_PERIOD_SEL_WBID0]),
    .wb_cyc_i(wbs_cyc_o[TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_PERIOD_SEL_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .wb_dat_o(wbs_dat_i[(TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_PERIOD_SEL_WBID0+1)*32-1:(TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_PERIOD_SEL_WBID0)*32]),
    .user_data_out(test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out),
    .wb_adr_i(wbs_adr_o)
  );

  // test_low_freq_marion2018_up_led1_new_acc
  gpio_simulink2ext #(
    .CLK_PHASE(0),
    .WIDTH(1),
    .DDR(0),
    .REG_IOB("true")
  ) test_low_freq_marion2018_up_led1_new_acc (
    .clk90(user_clk90),
    .io_pad(test_low_freq_marion2018_up_led1_new_acc_ext),
    .gateway(test_low_freq_marion2018_up_led1_new_acc_gateway),
    .clk(user_clk)
  );

  // test_low_freq_marion2018_up_sync_cnt
  wb_register_simulink2ppc  test_low_freq_marion2018_up_sync_cnt (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[TEST_LOW_FREQ_MARION2018_UP_SYNC_CNT_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[TEST_LOW_FREQ_MARION2018_UP_SYNC_CNT_WBID0]),
    .user_clk(user_clk),
    .wb_stb_i(wbs_stb_o[TEST_LOW_FREQ_MARION2018_UP_SYNC_CNT_WBID0]),
    .wb_cyc_i(wbs_cyc_o[TEST_LOW_FREQ_MARION2018_UP_SYNC_CNT_WBID0]),
    .user_data_in(test_low_freq_marion2018_up_sync_cnt_user_data_in),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .wb_dat_o(wbs_dat_i[(TEST_LOW_FREQ_MARION2018_UP_SYNC_CNT_WBID0+1)*32-1:(TEST_LOW_FREQ_MARION2018_UP_SYNC_CNT_WBID0)*32]),
    .wb_adr_i(wbs_adr_o)
  );

  // test_low_freq_marion2018_up_a_imaginary
  wb_bram #(
    .LOG_USER_WIDTH(6),
    .USER_ADDR_BITS(10),
    .N_REGISTERS(0)
  ) test_low_freq_marion2018_up_a_imaginary (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[TEST_LOW_FREQ_MARION2018_UP_A_IMAGINARY_WBID0]),
    .user_din(test_low_freq_marion2018_up_a_imaginary_data_in),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[TEST_LOW_FREQ_MARION2018_UP_A_IMAGINARY_WBID0]),
    .user_clk(user_clk),
    .wb_stb_i(wbs_stb_o[TEST_LOW_FREQ_MARION2018_UP_A_IMAGINARY_WBID0]),
    .wb_cyc_i(wbs_cyc_o[TEST_LOW_FREQ_MARION2018_UP_A_IMAGINARY_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .user_addr(test_low_freq_marion2018_up_a_imaginary_addr),
    .user_dout(test_low_freq_marion2018_up_a_imaginary_data_out),
    .user_we(test_low_freq_marion2018_up_a_imaginary_we),
    .wb_dat_o(wbs_dat_i[(TEST_LOW_FREQ_MARION2018_UP_A_IMAGINARY_WBID0+1)*32-1:(TEST_LOW_FREQ_MARION2018_UP_A_IMAGINARY_WBID0)*32]),
    .wb_adr_i(wbs_adr_o)
  );

  // test_low_freq_marion2018_up_gain
  wb_register_ppc2simulink  test_low_freq_marion2018_up_gain (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[TEST_LOW_FREQ_MARION2018_UP_GAIN_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[TEST_LOW_FREQ_MARION2018_UP_GAIN_WBID0]),
    .user_clk(user_clk),
    .wb_stb_i(wbs_stb_o[TEST_LOW_FREQ_MARION2018_UP_GAIN_WBID0]),
    .wb_cyc_i(wbs_cyc_o[TEST_LOW_FREQ_MARION2018_UP_GAIN_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .wb_dat_o(wbs_dat_i[(TEST_LOW_FREQ_MARION2018_UP_GAIN_WBID0+1)*32-1:(TEST_LOW_FREQ_MARION2018_UP_GAIN_WBID0)*32]),
    .user_data_out(test_low_freq_marion2018_up_gain_user_data_out),
    .wb_adr_i(wbs_adr_o)
  );

  // snap_adc_adc16_use_synth
  wb_register_ppc2simulink_sync  snap_adc_adc16_use_synth (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[SNAP_ADC_ADC16_USE_SYNTH_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[SNAP_ADC_ADC16_USE_SYNTH_WBID0]),
    .wb_stb_i(wbs_stb_o[SNAP_ADC_ADC16_USE_SYNTH_WBID0]),
    .wb_cyc_i(wbs_cyc_o[SNAP_ADC_ADC16_USE_SYNTH_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .wb_dat_o(wbs_dat_i[(SNAP_ADC_ADC16_USE_SYNTH_WBID0+1)*32-1:(SNAP_ADC_ADC16_USE_SYNTH_WBID0)*32]),
    .user_data_out(snap_adc_adc16_use_synth_user_data_out),
    .wb_adr_i(wbs_adr_o)
  );

  // None
  wbs_arbiter #(
    .NUM_SLAVES(N_WB_SLAVES),
    .SLAVE_ADDR(SLAVE_BASE),
    .SLAVE_HIGH(SLAVE_HIGH),
    .TIMEOUT(1024)
  ) wbs_arbiter_inst (
    .wbm_ack_o(wbm_ack_i),
    .wbm_adr_i(wbm_adr_o),
    .wbs_adr_o(wbs_adr_o),
    .wb_rst_i(wb_rst_i),
    .wbs_cyc_o(wbs_cyc_o),
    .wbs_ack_i(wbs_ack_i),
    .wbm_cyc_i(wbm_cyc_o),
    .wbm_dat_o(wbm_dat_i),
    .wbs_err_i(wbs_err_i),
    .wbs_dat_i(wbs_dat_i),
    .wb_clk_i(wb_clk_i),
    .wbm_we_i(wbm_we_o),
    .wbs_stb_o(wbs_stb_o),
    .wbs_we_o(wbs_we_o),
    .wbs_sel_o(wbs_sel_o),
    .wbs_dat_o(wbs_dat_o),
    .wbm_dat_i(wbm_dat_o),
    .wbm_sel_i(wbm_sel_o),
    .wbm_stb_i(wbm_stb_o),
    .wbm_err_o(wbm_err_i)
  );

  // test_low_freq_marion2018_up_fft_shift
  wb_register_ppc2simulink  test_low_freq_marion2018_up_fft_shift (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[TEST_LOW_FREQ_MARION2018_UP_FFT_SHIFT_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[TEST_LOW_FREQ_MARION2018_UP_FFT_SHIFT_WBID0]),
    .user_clk(user_clk),
    .wb_stb_i(wbs_stb_o[TEST_LOW_FREQ_MARION2018_UP_FFT_SHIFT_WBID0]),
    .wb_cyc_i(wbs_cyc_o[TEST_LOW_FREQ_MARION2018_UP_FFT_SHIFT_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .wb_dat_o(wbs_dat_i[(TEST_LOW_FREQ_MARION2018_UP_FFT_SHIFT_WBID0+1)*32-1:(TEST_LOW_FREQ_MARION2018_UP_FFT_SHIFT_WBID0)*32]),
    .user_data_out(test_low_freq_marion2018_up_fft_shift_user_data_out),
    .wb_adr_i(wbs_adr_o)
  );

  // LMX2581 synthesizer controller
  lmx2581_controller  lmx2581_controller_inst (
    .lmx_ce(lmx_ce),
    .lmx_clk(lmx_clk),
    .wb_sel_i(wbs_sel_o),
    .lmx_be(lmx_be),
    .wb_rst_i(wb_rst_i),
    .lmx_muxout(lmx_muxout),
    .wb_we_i(wbs_we_o),
    .lmx_le(lmx_le),
    .wb_stb_i(wbs_stb_o[LMX2581_CONTROLLER_INST_WBID0]),
    .wb_cyc_i(wbs_cyc_o[LMX2581_CONTROLLER_INST_WBID0]),
    .lmx_data(lmx_data),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .wb_ack_o(wbs_ack_i[LMX2581_CONTROLLER_INST_WBID0]),
    .wb_dat_o(wbs_dat_i[(LMX2581_CONTROLLER_INST_WBID0+1)*32-1:(LMX2581_CONTROLLER_INST_WBID0)*32]),
    .wb_adr_i(wbs_adr_o),
    .wb_err_o(wbs_err_i[LMX2581_CONTROLLER_INST_WBID0])
  );

  // test_low_freq_marion2018_up_acc_len
  wb_register_ppc2simulink  test_low_freq_marion2018_up_acc_len (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[TEST_LOW_FREQ_MARION2018_UP_ACC_LEN_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[TEST_LOW_FREQ_MARION2018_UP_ACC_LEN_WBID0]),
    .user_clk(user_clk),
    .wb_stb_i(wbs_stb_o[TEST_LOW_FREQ_MARION2018_UP_ACC_LEN_WBID0]),
    .wb_cyc_i(wbs_cyc_o[TEST_LOW_FREQ_MARION2018_UP_ACC_LEN_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .wb_dat_o(wbs_dat_i[(TEST_LOW_FREQ_MARION2018_UP_ACC_LEN_WBID0+1)*32-1:(TEST_LOW_FREQ_MARION2018_UP_ACC_LEN_WBID0)*32]),
    .user_data_out(test_low_freq_marion2018_up_acc_len_user_data_out),
    .wb_adr_i(wbs_adr_o)
  );

  // None
  snap_infrastructure  snap_infrastructure_inst (
    .clk_200(clk_200   ),
    .sys_clk_buf_n(sys_clk_n),
    .sys_rst(sys_rst   ),
    .sys_clk270(sys_clk270),
    .sys_clk_buf_p(sys_clk_p),
    .sys_clk180(sys_clk180),
    .sys_clk0(sys_clk   ),
    .idelay_rdy(idelay_rdy)
  );

  // None
  wb_adc16_controller #(
    .G_ROACH2_REV(0),
    .G_ZDOK_REV(2),
    .G_NUM_UNITS(3),
    .G_NUM_SCLK_LINES(3),
    .G_NUM_SDATA_LINES(3)
  ) wb_adc16_controller (
    .adc16_delay_rst(adc16_delay_rst),
    .adc16_snap_req(adc16_snap_req),
    .adc16_locked(adc16_locked),
    .wb_rst_i(wb_rst_i),
    .adc1_adc3wire_csn4(),
    .adc1_adc3wire_csn1(),
    .wb_cyc_i(wbs_cyc_o[WB_ADC16_CONTROLLER_WBID0]),
    .adc1_adc3wire_csn3(),
    .adc1_adc3wire_csn2(),
    .adc0_adc3wire_sdata(adc0_adc3wire_sdata),
    .adc16_demux_mode(adc16_demux_mode),
    .wb_adr_i(wbs_adr_o),
    .wb_ack_o(wbs_ack_i[WB_ADC16_CONTROLLER_WBID0]),
    .adc1_adc3wire_sclk(),
    .adc16_iserdes_bitslip(adc16_iserdes_bitslip),
    .adc0_adc3wire_csn1(adc0_adc3wire_csn1),
    .adc0_adc3wire_csn2(adc0_adc3wire_csn2),
    .adc0_adc3wire_csn3(adc0_adc3wire_csn3),
    .adc0_adc3wire_csn4(),
    .adc0_adc3wire_sclk(adc0_adc3wire_sclk),
    .wb_dat_o(wbs_dat_i[(WB_ADC16_CONTROLLER_WBID0+1)*32-1:(WB_ADC16_CONTROLLER_WBID0)*32]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .adc16_reset(adc16_reset),
    .wb_stb_i(wbs_stb_o[WB_ADC16_CONTROLLER_WBID0]),
    .wb_err_o(wbs_err_i[WB_ADC16_CONTROLLER_WBID0]),
    .adc16_delay_tap(adc16_delay_tap),
    .adc1_adc3wire_sdata()
  );

  // test_low_freq_marion2018_up_sync_gen1_sync
  wb_register_ppc2simulink  test_low_freq_marion2018_up_sync_gen1_sync (
    .wb_we_i(wbs_we_o),
    .wb_sel_i(wbs_sel_o),
    .wb_ack_o(wbs_ack_i[TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_err_o(wbs_err_i[TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_WBID0]),
    .user_clk(user_clk),
    .wb_stb_i(wbs_stb_o[TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_WBID0]),
    .wb_cyc_i(wbs_cyc_o[TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_clk_i(wb_clk_i),
    .wb_dat_o(wbs_dat_i[(TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_WBID0+1)*32-1:(TEST_LOW_FREQ_MARION2018_UP_SYNC_GEN1_SYNC_WBID0)*32]),
    .user_data_out(test_low_freq_marion2018_up_sync_gen1_sync_user_data_out),
    .wb_adr_i(wbs_adr_o)
  );

  // test_low_freq_marion2018_up_led0_sync
  gpio_simulink2ext #(
    .CLK_PHASE(0),
    .WIDTH(1),
    .DDR(0),
    .REG_IOB("true")
  ) test_low_freq_marion2018_up_led0_sync (
    .clk90(user_clk90),
    .io_pad(test_low_freq_marion2018_up_led0_sync_ext),
    .gateway(test_low_freq_marion2018_up_led0_sync_gateway),
    .clk(user_clk)
  );

  // None
  test_low_freq_marion2018_up  test_low_freq_marion2018_up_inst (
    .test_low_freq_marion2018_up_a_pol0_addr(test_low_freq_marion2018_up_a_pol0_addr),
    .test_low_freq_marion2018_up_a_pol1_addr(test_low_freq_marion2018_up_a_pol1_addr),
    .test_low_freq_marion2018_up_acc_cnt_user_data_in(test_low_freq_marion2018_up_acc_cnt_user_data_in),
    .test_low_freq_marion2018_up_snap_adc_c1(test_low_freq_marion2018_up_snap_adc_c1),
    .test_low_freq_marion2018_up_snap_adc_c3(test_low_freq_marion2018_up_snap_adc_c3),
    .test_low_freq_marion2018_up_snap_adc_c2(test_low_freq_marion2018_up_snap_adc_c2),
    .test_low_freq_marion2018_up_snap_adc_a3(test_low_freq_marion2018_up_snap_adc_a3),
    .test_low_freq_marion2018_up_snap_adc_a2(test_low_freq_marion2018_up_snap_adc_a2),
    .test_low_freq_marion2018_up_snap_adc_a1(test_low_freq_marion2018_up_snap_adc_a1),
    .test_low_freq_marion2018_up_a_real_addr(test_low_freq_marion2018_up_a_real_addr),
    .test_low_freq_marion2018_up_fft_shift_user_data_out(test_low_freq_marion2018_up_fft_shift_user_data_out),
    .test_low_freq_marion2018_up_a_real_data_out(test_low_freq_marion2018_up_a_real_data_out),
    .test_low_freq_marion2018_up_sync_cnt_user_data_in(test_low_freq_marion2018_up_sync_cnt_user_data_in),
    .test_low_freq_marion2018_up_cnt_rst_user_data_out(test_low_freq_marion2018_up_cnt_rst_user_data_out),
    .test_low_freq_marion2018_up_a_pol0_data_out(test_low_freq_marion2018_up_a_pol0_data_out),
    .clk(user_clk),
    .test_low_freq_marion2018_up_a_imaginary_data_in(test_low_freq_marion2018_up_a_imaginary_data_in),
    .test_low_freq_marion2018_up_gain_user_data_out(test_low_freq_marion2018_up_gain_user_data_out),
    .test_low_freq_marion2018_up_a_pol0_we(test_low_freq_marion2018_up_a_pol0_we),
    .test_low_freq_marion2018_up_a_pol1_data_out(test_low_freq_marion2018_up_a_pol1_data_out),
    .test_low_freq_marion2018_up_a_pol0_data_in(test_low_freq_marion2018_up_a_pol0_data_in),
    .test_low_freq_marion2018_up_a_pol1_data_in(test_low_freq_marion2018_up_a_pol1_data_in),
    .test_low_freq_marion2018_up_acc_len_user_data_out(test_low_freq_marion2018_up_acc_len_user_data_out),
    .test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out(test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out),
    .test_low_freq_marion2018_up_led1_new_acc_gateway(test_low_freq_marion2018_up_led1_new_acc_gateway),
    .test_low_freq_marion2018_up_a_imaginary_data_out(test_low_freq_marion2018_up_a_imaginary_data_out),
    .test_low_freq_marion2018_up_a_imaginary_we(test_low_freq_marion2018_up_a_imaginary_we),
    .test_low_freq_marion2018_up_snap_adc_c4(test_low_freq_marion2018_up_snap_adc_c4),
    .test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out(test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out),
    .test_low_freq_marion2018_up_snap_adc_a4(test_low_freq_marion2018_up_snap_adc_a4),
    .test_low_freq_marion2018_up_led0_sync_gateway(test_low_freq_marion2018_up_led0_sync_gateway),
    .test_low_freq_marion2018_up_a_real_data_in(test_low_freq_marion2018_up_a_real_data_in),
    .test_low_freq_marion2018_up_a_pol1_we(test_low_freq_marion2018_up_a_pol1_we),
    .test_low_freq_marion2018_up_sync_gen1_sync_user_data_out(test_low_freq_marion2018_up_sync_gen1_sync_user_data_out),
    .test_low_freq_marion2018_up_a_imaginary_addr(test_low_freq_marion2018_up_a_imaginary_addr),
    .test_low_freq_marion2018_up_snap_adc_b4(test_low_freq_marion2018_up_snap_adc_b4),
    .test_low_freq_marion2018_up_a_real_we(test_low_freq_marion2018_up_a_real_we),
    .test_low_freq_marion2018_up_snap_adc_b2(test_low_freq_marion2018_up_snap_adc_b2),
    .test_low_freq_marion2018_up_snap_adc_b3(test_low_freq_marion2018_up_snap_adc_b3),
    .test_low_freq_marion2018_up_snap_adc_b1(test_low_freq_marion2018_up_snap_adc_b1)
  );

  assign clk_sel_a[0] = snap_adc_adc16_use_synth_user_data_out[0];
  assign clk_sel_b[0] = ~snap_adc_adc16_use_synth_user_data_out[0];
  assign adc_rst_n = 3'b111;
  assign adc_pd = 3'b000;
  assign user_clk = adc0_clk;
  assign user_clk90 = adc0_clk90;
  assign user_clk180 = adc0_clk180;
  assign user_clk270 = adc0_clk270;
  assign sys_clk90 = ~sys_clk270;
  assign wb_clk_i = sys_clk;
  assign wb_rst_i = sys_rst;


endmodule
