# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/philip/firmware_marion2018/test_low_freq_marion2018_up/myproj/myproj.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9.xci
# IP: The module: 'test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/philip/firmware_marion2018/test_low_freq_marion2018_up/myproj/myproj.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/philip/firmware_marion2018/test_low_freq_marion2018_up/myproj/myproj.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9.xci
# IP: The module: 'test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/philip/firmware_marion2018/test_low_freq_marion2018_up/myproj/myproj.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
