puts "Starting tcl script"
create_project -f myproj /home/philip/firmware_marion2018/test_low_freq_marion2018_up/myproj -part xc7k160tffg676-2
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/top.v
import_files -force /home/philip/firmware_marion2018/mlib_devel/jasper_library/hdl_sources/adc16_interface
import_files -force /home/philip/firmware_marion2018/mlib_devel/jasper_library/hdl_sources/wb_adc16_controller
import_files -force /home/philip/firmware_marion2018/mlib_devel/jasper_library/hdl_sources/wb_bram
import_files -force /home/philip/firmware_marion2018/mlib_devel/jasper_library/hdl_sources/wb_register_simulink2ppc
import_files -force /home/philip/firmware_marion2018/mlib_devel/jasper_library/hdl_sources/wb_register_ppc2simulink
import_files -force /home/philip/firmware_marion2018/mlib_devel/jasper_library/hdl_sources/gpio_simulink2ext
import_files -force /home/philip/firmware_marion2018/mlib_devel/jasper_library/hdl_sources/lmx2581_controller
import_files -force /home/philip/firmware_marion2018/mlib_devel/jasper_library/hdl_sources/wb_register_ppc2simulink_sync
import_files -force /home/philip/firmware_marion2018/mlib_devel/jasper_library/hdl_sources/infrastructure
import_files -force /home/philip/firmware_marion2018/mlib_devel/jasper_library/hdl_sources/wbs_arbiter
import_files -force /home/philip/firmware_marion2018/mlib_devel/jasper_library/hdl_sources/sys_block
import_files -force /home/philip/firmware_marion2018/mlib_devel/jasper_library/hdl_sources/spi_wb_bridge
import_files -force /home/philip/firmware_marion2018/mlib_devel/jasper_library/hdl_sources/xadc/xadc.v
import_files -force /home/philip/firmware_marion2018/mlib_devel/jasper_library/hdl_sources/xadc/xadc_wiz_0.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/imports/sysgen
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i18_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i13_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i12_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i5_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_dist_mem_gen_v8_0_i3_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i27_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i19_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i26_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i2_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i21_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i8_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i4_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i15_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i1_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i25_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i20_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i24_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_dist_mem_gen_v8_0_i1_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i14_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_dist_mem_gen_v8_0_i0_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i16_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i6_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i3_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i17_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i11_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_dist_mem_gen_v8_0_i2_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i0_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i22_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i10_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i7_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i23_vivado.coe
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_addsub_v12_0_i5/test_low_freq_marion2018_up_c_addsub_v12_0_i5.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i15/test_low_freq_marion2018_up_c_counter_binary_v12_0_i15.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i27/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i27.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i3/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i3.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i12/test_low_freq_marion2018_up_c_counter_binary_v12_0_i12.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i21/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i21.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i0/test_low_freq_marion2018_up_c_counter_binary_v12_0_i0.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i15/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i15.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_addsub_v12_0_i0/test_low_freq_marion2018_up_c_addsub_v12_0_i0.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_addsub_v12_0_i7/test_low_freq_marion2018_up_c_addsub_v12_0_i7.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i14/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i14.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i7/test_low_freq_marion2018_up_c_counter_binary_v12_0_i7.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i3/test_low_freq_marion2018_up_c_counter_binary_v12_0_i3.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i22/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i22.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_dist_mem_gen_v8_0_i2/test_low_freq_marion2018_up_dist_mem_gen_v8_0_i2.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i18/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i18.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i13/test_low_freq_marion2018_up_c_counter_binary_v12_0_i13.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_addsub_v12_0_i3/test_low_freq_marion2018_up_c_addsub_v12_0_i3.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i16/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i16.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i2/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i2.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i11/test_low_freq_marion2018_up_c_counter_binary_v12_0_i11.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i8/test_low_freq_marion2018_up_c_counter_binary_v12_0_i8.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i24/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i24.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_dist_mem_gen_v8_0_i1/test_low_freq_marion2018_up_dist_mem_gen_v8_0_i1.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i25/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i25.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i4/test_low_freq_marion2018_up_c_counter_binary_v12_0_i4.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i8/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i8.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_addsub_v12_0_i1/test_low_freq_marion2018_up_c_addsub_v12_0_i1.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i10/test_low_freq_marion2018_up_c_counter_binary_v12_0_i10.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i4/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i4.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i9/test_low_freq_marion2018_up_c_counter_binary_v12_0_i9.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i17/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i17.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i2/test_low_freq_marion2018_up_c_counter_binary_v12_0_i2.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i14/test_low_freq_marion2018_up_c_counter_binary_v12_0_i14.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i19/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i19.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i11/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i11.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_mult_gen_v12_0_i0/test_low_freq_marion2018_up_mult_gen_v12_0_i0.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i20/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i20.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i16/test_low_freq_marion2018_up_c_counter_binary_v12_0_i16.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i5/test_low_freq_marion2018_up_c_counter_binary_v12_0_i5.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i10/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i10.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_addsub_v12_0_i6/test_low_freq_marion2018_up_c_addsub_v12_0_i6.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i0/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i0.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i7/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i7.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i6/test_low_freq_marion2018_up_c_counter_binary_v12_0_i6.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i23/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i23.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i12/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i12.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_dist_mem_gen_v8_0_i3/test_low_freq_marion2018_up_dist_mem_gen_v8_0_i3.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_dist_mem_gen_v8_0_i0/test_low_freq_marion2018_up_dist_mem_gen_v8_0_i0.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_counter_binary_v12_0_i1/test_low_freq_marion2018_up_c_counter_binary_v12_0_i1.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_addsub_v12_0_i8/test_low_freq_marion2018_up_c_addsub_v12_0_i8.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i1/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i1.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i6/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i6.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i5/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i5.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_addsub_v12_0_i4/test_low_freq_marion2018_up_c_addsub_v12_0_i4.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i26/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i26.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i13/test_low_freq_marion2018_up_blk_mem_gen_v8_3_i13.xci
import_files -force /home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen/hdl_netlist/test_low_freq_marion2018_up.srcs/sources_1/ip/test_low_freq_marion2018_up_c_addsub_v12_0_i2/test_low_freq_marion2018_up_c_addsub_v12_0_i2.xci
import_files -force -fileset constrs_1 /home/philip/firmware_marion2018/test_low_freq_marion2018_up/user_const.xdc
set_property top top [current_fileset]
update_compile_order -fileset sources_1
if {[llength [glob -nocomplain [get_property directory [current_project]]/myproj.srcs/sources_1/imports/*.coe]] > 0} {
file copy -force {*}[glob [get_property directory [current_project]]/myproj.srcs/sources_1/imports/*.coe] [get_property directory [current_project]]/myproj.srcs/sources_1/ip/
}
upgrade_ip -quiet [get_ips *]
reset_run synth_1
launch_runs synth_1 -jobs 4
wait_on_run synth_1
open_run synth_1
set_property STEPS.WRITE_BITSTREAM.ARGS.BIN_FILE true [get_runs impl_1]
set_property STEPS.PHYS_OPT_DESIGN.IS_ENABLED true [get_runs impl_1]
launch_runs impl_1 -jobs 4
wait_on_run impl_1
open_run impl_1
launch_runs impl_1 -to_step write_bitstream
wait_on_run impl_1
cd [get_property DIRECTORY [current_project]]
if { [get_property STATS.WNS [get_runs impl_1] ] < 0 } {
puts "Found timing violations => Worst Negative Slack: [get_property STATS.WNS [get_runs impl_1]] ns" 
} else {
puts "No timing violations => Worst Negative Slack: [get_property STATS.WNS [get_runs impl_1]] ns" 
}
if { [get_property STATS.TNS [get_runs impl_1] ] < 0 } {
puts "Found timing violations => Total Negative Slack: [get_property STATS.TNS [get_runs impl_1]] ns" 
} else {
puts "No timing violations => Total Negative Slack: [get_property STATS.TNS [get_runs impl_1]] ns" 
}
if { [get_property STATS.WHS [get_runs impl_1] ] < 0 } {
puts "Found timing violations => Worst Hold Slack: [get_property STATS.WHS [get_runs impl_1]] ns" 
} else {
puts "No timing violations => Worst Hold Slack: [get_property STATS.WHS [get_runs impl_1]] ns" 
}
if { [get_property STATS.THS [get_runs impl_1] ] < 0 } {
puts "Found timing violations => Total Hold Slack: [get_property STATS.THS [get_runs impl_1]] ns" 
} else {
puts "No timing violations => Total Hold Slack: [get_property STATS.THS [get_runs impl_1]] ns" 
}
write_cfgmem  -format mcs -size 32 -interface SPIx4 -loadbit "up 0x0 ./myproj.runs/impl_1/top.bit " -checksum -file "./myproj.runs/impl_1/top.mcs" -force
write_cfgmem  -format mcs -size 32 -interface SPIx4 -loadbit "up 0x0008000 ./myproj.runs/impl_1/top.bit " -checksum -file "./myproj.runs/impl_1/top_0x8000.mcs" -force
write_cfgmem  -format bin -size 32 -interface SPIx4 -loadbit "up 0x0 ./myproj.runs/impl_1/top.bit " -checksum -file "./myproj.runs/impl_1/top.bin" -force
