# Note: This file is produced automatically, and will be overwritten the next
# time you press "Generate" in System Generator. 
#


namespace eval ::xilinx::dsp::planaheaddriver {
	set Compilation {HDL Netlist}
	set CompilationFlow {STANDARD}
	set DSPDevice {xc7k160t}
	set DSPFamily {kintex7}
	set DSPPackage {ffg676}
	set DSPSpeed {-2}
	set FPGAClockPeriod 4
	set GenerateTestBench 0
	set HDLLanguage {vhdl}
	set IPOOCCacheRootPath {/home/philip/.Xilinx/Sysgen/SysgenVivado/lnx64.o/ip}
	set ImplStrategyName {Vivado Implementation Defaults}
	set Project {test_low_freq_marion2018_up}
	set ProjectFiles {
		{{conv_pkg.vhd} -lib {work}}
		{{synth_reg.vhd} -lib {work}}
		{{synth_reg_w_init.vhd} -lib {work}}
		{{srl17e.vhd} -lib {work}}
		{{srl33e.vhd} -lib {work}}
		{{synth_reg_reg.vhd} -lib {work}}
		{{single_reg_w_init.vhd} -lib {work}}
		{{xlclockdriver_rd.vhd} -lib {work}}
		{{vivado_ip.tcl}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i0_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i1_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i2_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i3_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i4_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i5_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i6_vivado.coe}}
		{{test_low_freq_marion2018_up_dist_mem_gen_v8_0_i0_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i7_vivado.coe}}
		{{test_low_freq_marion2018_up_dist_mem_gen_v8_0_i1_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i8_vivado.coe}}
		{{test_low_freq_marion2018_up_dist_mem_gen_v8_0_i2_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i9_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i10_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i11_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i12_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i13_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i14_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i15_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i16_vivado.coe}}
		{{test_low_freq_marion2018_up_dist_mem_gen_v8_0_i3_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i17_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i18_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i19_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i20_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i21_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i22_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i23_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i24_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i25_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i26_vivado.coe}}
		{{test_low_freq_marion2018_up_blk_mem_gen_v8_3_i27_vivado.coe}}
		{{test_low_freq_marion2018_up_entity_declarations.vhd} -lib {work}}
		{{test_low_freq_marion2018_up.vhd} -lib {work}}
		{{test_low_freq_marion2018_up_clock.xdc}}
		{{test_low_freq_marion2018_up.xdc}}
	}
	set SimPeriod 1
	set SimTime 15000
	set SimulationTime {60204.00000000 ns}
	set SynthStrategyName {Vivado Synthesis Defaults}
	set SynthesisTool {Vivado}
	set TargetDir {/home/philip/firmware_marion2018/test_low_freq_marion2018_up/sysgen}
	set TopLevelModule {test_low_freq_marion2018_up}
	set TopLevelSimulinkHandle 73096
	set VHDLLib {work}
	set TopLevelPortInterface {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out Name {test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out Type UFix_32_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out Width 32
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out DatFile {test_low_freq_marion2018_up_sync_gen1_sync_period_var_test_low_freq_marion2018_up_sync_gen1_sync_per.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out IconText {test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_var_user_data_out IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out Name {test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out Type UFix_32_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out Width 32
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out DatFile {test_low_freq_marion2018_up_sync_gen1_sync_period_sel_test_low_freq_marion2018_up_sync_gen1_sync_per.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out IconText {test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_period_sel_user_data_out IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out Name {test_low_freq_marion2018_up_sync_gen1_sync_user_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out Type UFix_32_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out Width 32
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out DatFile {test_low_freq_marion2018_up_sync_gen1_sync_test_low_freq_marion2018_up_sync_gen1_sync_user_data_out.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out IconText {test_low_freq_marion2018_up_sync_gen1_sync_user_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_gen1_sync_user_data_out IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 Name {test_low_freq_marion2018_up_snap_adc_c4}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 Type Fix_8_7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 ArithmeticType xlSigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 BinaryPoint 7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 Width 8
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 DatFile {test_low_freq_marion2018_up_snap_adc_test_low_freq_marion2018_up_snap_adc_c4.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 IconText {test_low_freq_marion2018_up_snap_adc_c4}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c4 IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 Name {test_low_freq_marion2018_up_snap_adc_c3}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 Type Fix_8_7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 ArithmeticType xlSigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 BinaryPoint 7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 Width 8
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 DatFile {test_low_freq_marion2018_up_snap_adc_test_low_freq_marion2018_up_snap_adc_c3.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 IconText {test_low_freq_marion2018_up_snap_adc_c3}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c3 IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 Name {test_low_freq_marion2018_up_snap_adc_c2}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 Type Fix_8_7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 ArithmeticType xlSigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 BinaryPoint 7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 Width 8
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 DatFile {test_low_freq_marion2018_up_snap_adc_test_low_freq_marion2018_up_snap_adc_c2.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 IconText {test_low_freq_marion2018_up_snap_adc_c2}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c2 IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 Name {test_low_freq_marion2018_up_snap_adc_c1}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 Type Fix_8_7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 ArithmeticType xlSigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 BinaryPoint 7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 Width 8
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 DatFile {test_low_freq_marion2018_up_snap_adc_test_low_freq_marion2018_up_snap_adc_c1.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 IconText {test_low_freq_marion2018_up_snap_adc_c1}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_c1 IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 Name {test_low_freq_marion2018_up_snap_adc_b4}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 Type Fix_8_7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 ArithmeticType xlSigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 BinaryPoint 7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 Width 8
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 DatFile {test_low_freq_marion2018_up_snap_adc_test_low_freq_marion2018_up_snap_adc_b4.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 IconText {test_low_freq_marion2018_up_snap_adc_b4}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b4 IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 Name {test_low_freq_marion2018_up_snap_adc_b3}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 Type Fix_8_7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 ArithmeticType xlSigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 BinaryPoint 7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 Width 8
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 DatFile {test_low_freq_marion2018_up_snap_adc_test_low_freq_marion2018_up_snap_adc_b3.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 IconText {test_low_freq_marion2018_up_snap_adc_b3}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b3 IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 Name {test_low_freq_marion2018_up_snap_adc_b2}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 Type Fix_8_7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 ArithmeticType xlSigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 BinaryPoint 7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 Width 8
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 DatFile {test_low_freq_marion2018_up_snap_adc_test_low_freq_marion2018_up_snap_adc_b2.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 IconText {test_low_freq_marion2018_up_snap_adc_b2}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b2 IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 Name {test_low_freq_marion2018_up_snap_adc_b1}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 Type Fix_8_7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 ArithmeticType xlSigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 BinaryPoint 7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 Width 8
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 DatFile {test_low_freq_marion2018_up_snap_adc_test_low_freq_marion2018_up_snap_adc_b1.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 IconText {test_low_freq_marion2018_up_snap_adc_b1}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_b1 IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 Name {test_low_freq_marion2018_up_snap_adc_a4}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 Type Fix_8_7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 ArithmeticType xlSigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 BinaryPoint 7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 Width 8
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 DatFile {test_low_freq_marion2018_up_snap_adc_test_low_freq_marion2018_up_snap_adc_a4.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 IconText {test_low_freq_marion2018_up_snap_adc_a4}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a4 IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 Name {test_low_freq_marion2018_up_snap_adc_a3}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 Type Fix_8_7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 ArithmeticType xlSigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 BinaryPoint 7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 Width 8
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 DatFile {test_low_freq_marion2018_up_snap_adc_test_low_freq_marion2018_up_snap_adc_a3.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 IconText {test_low_freq_marion2018_up_snap_adc_a3}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a3 IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 Name {test_low_freq_marion2018_up_snap_adc_a2}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 Type Fix_8_7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 ArithmeticType xlSigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 BinaryPoint 7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 Width 8
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 DatFile {test_low_freq_marion2018_up_snap_adc_test_low_freq_marion2018_up_snap_adc_a2.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 IconText {test_low_freq_marion2018_up_snap_adc_a2}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a2 IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 Name {test_low_freq_marion2018_up_snap_adc_a1}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 Type Fix_8_7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 ArithmeticType xlSigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 BinaryPoint 7
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 Width 8
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 DatFile {test_low_freq_marion2018_up_snap_adc_test_low_freq_marion2018_up_snap_adc_a1.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 IconText {test_low_freq_marion2018_up_snap_adc_a1}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_snap_adc_a1 IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out Name {test_low_freq_marion2018_up_gain_user_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out Type UFix_32_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out Width 32
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out DatFile {test_low_freq_marion2018_up_gain_test_low_freq_marion2018_up_gain_user_data_out.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out IconText {test_low_freq_marion2018_up_gain_user_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_gain_user_data_out IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out Name {test_low_freq_marion2018_up_fft_shift_user_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out Type UFix_32_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out Width 32
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out DatFile {test_low_freq_marion2018_up_fft_shift_test_low_freq_marion2018_up_fft_shift_user_data_out.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out IconText {test_low_freq_marion2018_up_fft_shift_user_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_fft_shift_user_data_out IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out Name {test_low_freq_marion2018_up_cnt_rst_user_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out Type UFix_32_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out Width 32
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out DatFile {test_low_freq_marion2018_up_cnt_rst_test_low_freq_marion2018_up_cnt_rst_user_data_out.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out IconText {test_low_freq_marion2018_up_cnt_rst_user_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_cnt_rst_user_data_out IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out Name {test_low_freq_marion2018_up_acc_len_user_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out Type UFix_32_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out Width 32
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out DatFile {test_low_freq_marion2018_up_acc_len_test_low_freq_marion2018_up_acc_len_user_data_out.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out IconText {test_low_freq_marion2018_up_acc_len_user_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_len_user_data_out IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out Name {test_low_freq_marion2018_up_a_real_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out Type UFix_64_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out Width 64
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out DatFile {test_low_freq_marion2018_up_a_real_test_low_freq_marion2018_up_a_real_data_out.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out IconText {test_low_freq_marion2018_up_a_real_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_out IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out Name {test_low_freq_marion2018_up_a_pol1_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out Type UFix_64_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out Width 64
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out DatFile {test_low_freq_marion2018_up_a_pol1_test_low_freq_marion2018_up_a_pol1_data_out.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out IconText {test_low_freq_marion2018_up_a_pol1_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_out IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out Name {test_low_freq_marion2018_up_a_pol0_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out Type UFix_64_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out Width 64
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out DatFile {test_low_freq_marion2018_up_a_pol0_test_low_freq_marion2018_up_a_pol0_data_out.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out IconText {test_low_freq_marion2018_up_a_pol0_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_out IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out Name {test_low_freq_marion2018_up_a_imaginary_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out Type UFix_64_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out Width 64
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out DatFile {test_low_freq_marion2018_up_a_imaginary_test_low_freq_marion2018_up_a_imaginary_data_out.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out IconText {test_low_freq_marion2018_up_a_imaginary_data_out}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out Direction in
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_out IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr Name {test_low_freq_marion2018_up_a_imaginary_addr}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr Type UFix_10_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr Width 10
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr DatFile {test_low_freq_marion2018_up_a_imaginary_test_low_freq_marion2018_up_a_imaginary_addr.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr IconText {test_low_freq_marion2018_up_a_imaginary_addr}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_addr IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in Name {test_low_freq_marion2018_up_a_imaginary_data_in}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in Type UFix_64_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in Width 64
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in DatFile {test_low_freq_marion2018_up_a_imaginary_test_low_freq_marion2018_up_a_imaginary_data_in.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in IconText {test_low_freq_marion2018_up_a_imaginary_data_in}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_data_in IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we Name {test_low_freq_marion2018_up_a_imaginary_we}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we Type UFix_1_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we Width 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we DatFile {test_low_freq_marion2018_up_a_imaginary_test_low_freq_marion2018_up_a_imaginary_we.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we IconText {test_low_freq_marion2018_up_a_imaginary_we}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_imaginary_we IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr Name {test_low_freq_marion2018_up_a_pol0_addr}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr Type UFix_10_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr Width 10
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr DatFile {test_low_freq_marion2018_up_a_pol0_test_low_freq_marion2018_up_a_pol0_addr.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr IconText {test_low_freq_marion2018_up_a_pol0_addr}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_addr IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in Name {test_low_freq_marion2018_up_a_pol0_data_in}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in Type UFix_64_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in Width 64
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in DatFile {test_low_freq_marion2018_up_a_pol0_test_low_freq_marion2018_up_a_pol0_data_in.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in IconText {test_low_freq_marion2018_up_a_pol0_data_in}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_data_in IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we Name {test_low_freq_marion2018_up_a_pol0_we}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we Type UFix_1_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we Width 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we DatFile {test_low_freq_marion2018_up_a_pol0_test_low_freq_marion2018_up_a_pol0_we.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we IconText {test_low_freq_marion2018_up_a_pol0_we}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol0_we IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr Name {test_low_freq_marion2018_up_a_pol1_addr}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr Type UFix_10_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr Width 10
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr DatFile {test_low_freq_marion2018_up_a_pol1_test_low_freq_marion2018_up_a_pol1_addr.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr IconText {test_low_freq_marion2018_up_a_pol1_addr}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_addr IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in Name {test_low_freq_marion2018_up_a_pol1_data_in}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in Type UFix_64_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in Width 64
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in DatFile {test_low_freq_marion2018_up_a_pol1_test_low_freq_marion2018_up_a_pol1_data_in.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in IconText {test_low_freq_marion2018_up_a_pol1_data_in}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_data_in IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we Name {test_low_freq_marion2018_up_a_pol1_we}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we Type UFix_1_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we Width 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we DatFile {test_low_freq_marion2018_up_a_pol1_test_low_freq_marion2018_up_a_pol1_we.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we IconText {test_low_freq_marion2018_up_a_pol1_we}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_pol1_we IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr Name {test_low_freq_marion2018_up_a_real_addr}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr Type UFix_10_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr Width 10
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr DatFile {test_low_freq_marion2018_up_a_real_test_low_freq_marion2018_up_a_real_addr.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr IconText {test_low_freq_marion2018_up_a_real_addr}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_addr IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in Name {test_low_freq_marion2018_up_a_real_data_in}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in Type UFix_64_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in Width 64
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in DatFile {test_low_freq_marion2018_up_a_real_test_low_freq_marion2018_up_a_real_data_in.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in IconText {test_low_freq_marion2018_up_a_real_data_in}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_data_in IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we Name {test_low_freq_marion2018_up_a_real_we}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we Type UFix_1_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we Width 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we DatFile {test_low_freq_marion2018_up_a_real_test_low_freq_marion2018_up_a_real_we.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we IconText {test_low_freq_marion2018_up_a_real_we}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_a_real_we IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in Name {test_low_freq_marion2018_up_acc_cnt_user_data_in}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in Type UFix_32_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in Width 32
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in DatFile {test_low_freq_marion2018_up_acc_cnt_test_low_freq_marion2018_up_acc_cnt_user_data_in.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in IconText {test_low_freq_marion2018_up_acc_cnt_user_data_in}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_acc_cnt_user_data_in IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway Name {test_low_freq_marion2018_up_led0_sync_gateway}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway Type Bool
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway Width 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway DatFile {test_low_freq_marion2018_up_led0_sync_test_low_freq_marion2018_up_led0_sync_gateway.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway IconText {test_low_freq_marion2018_up_led0_sync_gateway}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led0_sync_gateway IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway Name {test_low_freq_marion2018_up_led1_new_acc_gateway}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway Type Bool
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway Width 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway DatFile {test_low_freq_marion2018_up_led1_new_acc_test_low_freq_marion2018_up_led1_new_acc_gateway.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway IconText {test_low_freq_marion2018_up_led1_new_acc_gateway}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_led1_new_acc_gateway IOStandard {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in Name {test_low_freq_marion2018_up_sync_cnt_user_data_in}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in Type UFix_32_0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in BinaryPoint 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in Width 32
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in DatFile {test_low_freq_marion2018_up_sync_cnt_test_low_freq_marion2018_up_sync_cnt_user_data_in.dat}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in IconText {test_low_freq_marion2018_up_sync_cnt_user_data_in}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in Direction out
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in Period 1
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in Interface 0
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in InterfaceName {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in InterfaceString {DATA}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in Locs {}
	dict set TopLevelPortInterface test_low_freq_marion2018_up_sync_cnt_user_data_in IOStandard {}
	dict set TopLevelPortInterface clk Name {clk}
	dict set TopLevelPortInterface clk Type -
	dict set TopLevelPortInterface clk ArithmeticType xlUnsigned
	dict set TopLevelPortInterface clk BinaryPoint 0
	dict set TopLevelPortInterface clk Width 1
	dict set TopLevelPortInterface clk DatFile {}
	dict set TopLevelPortInterface clk Direction in
	dict set TopLevelPortInterface clk Period 1
	dict set TopLevelPortInterface clk Interface 6
	dict set TopLevelPortInterface clk InterfaceName {}
	dict set TopLevelPortInterface clk InterfaceString {CLOCK}
	dict set TopLevelPortInterface clk ClockDomain {test_low_freq_marion2018_up}
	dict set TopLevelPortInterface clk Locs {}
	dict set TopLevelPortInterface clk IOStandard {}
	dict set TopLevelPortInterface clk AssociatedInterfaces {}
	dict set TopLevelPortInterface clk AssociatedResets {}
	set MemoryMappedPort {}
}

source SgPaProject.tcl
::xilinx::dsp::planaheadworker::dsp_create_project